---
abstract: 'convert Changes from YAML to CPAN::Changes::Spec format'
author:
  - 'Carlos Lima <carlos@cpan.org>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::DZil: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ChangesFromYaml
no_index:
  directory:
    - corpus
requires:
  CPAN::Changes: 0
  Carp: 0
  DateTime::Format::CLDR: 0
  Dist::Zilla::Role::FileMunger: 0
  Exporter: 0
  Moose: 0
  YAML::XS: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/carloslima/dist-zilla-plugin-changesfromyaml/issues
  homepage: https://github.com/carloslima/dist-zilla-plugin-changesfromyaml
  repository: https://github.com/carloslima/dist-zilla-plugin-changesfromyaml.git
version: 0.003
